openapi: "3.1.0"
info:
  title: OneLaw Cloud Webhooks
  version: 1.0.0
  license: 
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: |
    ## Usage

    - Subscribers register one HTTPS endpoint in the OneLaw App and all selected webhook events are sent to that endpoint
    - The event type is specified by the `type` field in the JSON body and determines the schema of the `data` field
    - Subscribers must validate the `Webhook-Signature` header for every webhook request they receive
      ([details](https://github.com/standard-webhooks/standard-webhooks/blob/main/spec/standard-webhooks.md#verifying-webhook-authenticity)) 
      and reject requests that have invalid signatures

webhooks:

  PartyEvent:
    post:
      operationId: partyEvent
      summary: A party has been created or changed
      parameters: 
      - name: Webhook-ID
        description: ID of the event, same for all retries
        in: header
        schema: 
          type: string
      - name: Webhook-Timestamp
        description: Time this request was sent in Unix epoch format
        in: header
        schema: 
          type: integer
      - name: Webhook-Signature
        description: HMAC signature of the payload
        in: header
        schema: 
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PartyWebhook" 
      responses:
        "200":
          description: webhook received

  MatterEvent:
    post:
      operationId: matterEvent
      summary: A matter has been created or changed
      parameters: 
      - name: Webhook-ID
        description: ID of the event, same for all retries
        in: header
        schema: 
          type: string
      - name: Webhook-Timestamp
        description: Time this request was sent in Unix epoch format
        in: header
        schema: 
          type: integer
      - name: Webhook-Signature
        description: HMAC signature of the payload
        in: header
        schema: 
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatterWebhook" 
      responses:
        "200":
          description: webhook received

  DocumentEvent:
    post:
      operationId: documentEvent
      summary: A document has been managed or updated
      parameters: 
      - name: Webhook-ID
        description: ID of the event, same for all retries
        in: header
        schema: 
          type: string
      - name: Webhook-Timestamp
        description: Time this request was sent in Unix epoch format
        in: header
        schema: 
          type: integer
      - name: Webhook-Signature
        description: HMAC signature of the payload
        in: header
        schema: 
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentWebhook" 
      responses:
        "200":
          description: webhook received

  DocumentMovedEvent:
    post:
      operationId: documentMovedEvent
      summary: A document has been moved to a different Party or Matter
      parameters: 
      - name: Webhook-ID
        description: ID of the event, same for all retries
        in: header
        schema: 
          type: string
      - name: Webhook-Timestamp
        description: Time this request was sent in Unix epoch format
        in: header
        schema: 
          type: integer
      - name: Webhook-Signature
        description: HMAC signature of the payload
        in: header
        schema: 
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentMovedWebhook" 
      responses:
        "200":
          description: webhook received

components: 
  schemas: 

    #
    # Webhook request base schemas
    #

    WebhookBase:
      type: object
      description: Base JSON schema used in all outbound webhook requests
      required: [ id, type, timestamp ]
      properties:
        id:
          type: string
          description: Uniquely identifies the event being described (will be the same for subsequent retries)
        type:
          type: string
          description: |
            The type of the event being sent (e.g "user.created" or "invoice.paid"),
            indicates the schema of the payload (passed in the `data` field).
        timestamp:
          type: string
          format: date-time
          description: |
            The timestamp of when the event occurred (not necessarily the same of when it was delivered) 
            in an ISO 8601 formatted string.

    #
    # Party Webhook schemas
    #

    PartyWebhook:
      allOf: 
        - $ref: '#/components/schemas/WebhookBase'
        - type: object
          description: JSON schema used in outbound webhook requests for Party changes
          required: [ data ]
          properties:
            data:
              $ref: '#/components/schemas/PartyWebhookData'

    PartyWebhookData:
      type: object
      description: Data sent inside a webhook request envelope for party changes
      required: [ partyId, partyNumber ]
      properties: 
        partyId:
          type: string
          format: uuid
        partyNumber:
          type: string
          description: Natural key or user reference for parties
        clientId:
          type: [string, "null"]
          format: uuid
          description: Included only if the party is a client of the law firm
        clientNumber:
          type: [string, "null"]
          description: Included only if the party is a client of the law firm

    #
    # Matter Webhook schemas
    #

    MatterWebhook:
      allOf: 
        - $ref: '#/components/schemas/WebhookBase'
        - type: object
          description: JSON schema used in outbound webhook requests for Matter changes
          required: [ data ]
          properties:
            data:
              $ref: '#/components/schemas/MatterWebhookData'

    MatterWebhookData:
      allOf: 
      - $ref: '#/components/schemas/PartyWebhookData'
      - type: object
        description: Data sent inside a webhook request envelope for Matter changes
        required: [ matterId, matterNumber ]
        properties: 
          matterId:
            type: string
            format: uuid
          matterNumber:
            type: string
            description: Natural key or user reference for matters

    #
    # Document Webhook schemas
    #

    DocumentWebhook:
      allOf: 
        - $ref: '#/components/schemas/WebhookBase'
        - type: object
          description: JSON schema used in outbound webhook requests for Document changes
          required: [ data ]
          properties:
            data:
              $ref: '#/components/schemas/DocumentWebhookData'

    DocumentWebhookData:
      allOf:
      - $ref: '#/components/schemas/DocumentLocationData'
      - type: object
        required: [ documentId, documentNumber, partyId, partyNumber ]
        properties: 
          documentId:
            type: string
            format: uuid
            description: ID of the document
          documentNumber:
            type: string
            description: Natural key or user reference for the document, in the format {number.version}.

    #
    # Document Moved Schemas
    #

    DocumentMovedWebhook:
      allOf: 
        - $ref: '#/components/schemas/WebhookBase'
        - type: object
          description: JSON schema used in outbound webhook requests for Document moves
          required: [ data ]
          properties:
            data:
              $ref: '#/components/schemas/DocumentMovedWebhookData'

    DocumentMovedWebhookData:
      type: object
      required: [ documentId, documentNumber ]
      properties: 
        documentId:
          type: string
          format: uuid
          description: ID of the document
        documentNumber:
          type: string
          description: Natural key or user reference for the document, in the format {number.version}.
        from:
          $ref: '#/components/schemas/DocumentLocationData'
        to:
          $ref: '#/components/schemas/DocumentLocationData'

    #
    # Shared Document Schema
    #

    DocumentLocationData:
      type: object
      required: [ partyId, partyNumber ]
      properties: 
        partyId:
          type: string
          format: uuid
          description: ID of the party the document is managed for
        partyNumber:
          type: string
          description: Natural key or user reference of the party the document is managed for
        clientId:
          type: [string, "null"]
          format: uuid
          description: Included only if the document is managed at the matter level
        clientNumber:
          type: [string, "null"]
          description: Included only if the document is managed at the matter level
        matterId:
          type: [string, "null"]
          format: uuid
          description: Included only if the document is managed at the matter level
        matterNumber:
          type: [string, "null"]
          description: Included only if the document is managed at the matter level
