openapi: "3.1.0"
info:
  title: OneLaw Cloud Webhooks
  version: 1.0.0
  license: 
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: |
    ## Usage

    - Subscribers register one HTTPS endpoint in the OneLaw App and all selected webhook events are sent to that endpoint
    - The event type is specified by the `type` field in the JSON body and determines the schema of the `data` field
    - Subscribers must validate the `Webhook-Signature` header for every webhook request they receive
      ([details](https://github.com/standard-webhooks/standard-webhooks/blob/main/spec/standard-webhooks.md#verifying-webhook-authenticity)) 
      and reject requests that have invalid signatures

webhooks:

  PartyEvent:
    post:
      operationId: partyEvent
      summary: A party has been created or changed
      parameters:
      - $ref: '#/components/parameters/webhookId'
      - $ref: '#/components/parameters/webhookTimestamp'
      - $ref: '#/components/parameters/webhookSignature'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PartyWebhookRequest" 
      responses:
        "200":
          description: webhook received

  MatterEvent:
    post:
      operationId: matterEvent
      summary: A matter has been created or changed
      parameters:
      - $ref: '#/components/parameters/webhookId'
      - $ref: '#/components/parameters/webhookTimestamp'
      - $ref: '#/components/parameters/webhookSignature'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatterWebhookRequest" 
      responses:
        "200":
          description: webhook received

  DocumentEvent:
    post:
      operationId: documentEvent
      summary: A document has been managed or updated
      parameters:
      - $ref: '#/components/parameters/webhookId'
      - $ref: '#/components/parameters/webhookTimestamp'
      - $ref: '#/components/parameters/webhookSignature'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentWebhookRequest" 
      responses:
        "200":
          description: webhook received

  DocumentMovedEvent:
    post:
      operationId: documentMovedEvent
      summary: A document has been moved to a different Party or Matter
      parameters:
      - $ref: '#/components/parameters/webhookId'
      - $ref: '#/components/parameters/webhookTimestamp'
      - $ref: '#/components/parameters/webhookSignature'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentMovedWebhookRequest" 
      responses:
        "200":
          description: webhook received

components: 

  parameters:
    webhookId:
      name: Webhook-ID
      description: ID of the event, same for all retries
      in: header
      schema: 
        type: string
      required: true
    webhookTimestamp:
      name: Webhook-Timestamp
      description: Time this request was sent in Unix epoch format
      in: header
      schema: 
        type: integer
      required: true
    webhookSignature:
      name: Webhook-Signature
      description: HMAC signature of the payload
      in: header
      schema: 
        type: string
      required: true

  schemas: 

    #
    # Webhook request base schemas
    #

    WebhookBase:
      type: object
      description: Base JSON schema used in all outbound webhook requests
      required: [ id, type, timestamp ]
      properties:
        id:
          type: string
          description: Uniquely identifies the event being described (will be the same for subsequent retries)
        type:
          type: string
          description: |
            The type of the event being sent (e.g "user.created" or "invoice.paid"),
            indicates the schema of the payload (passed in the `data` field).
        timestamp:
          type: string
          format: date-time
          description: |
            The timestamp of when the event occurred (not necessarily the same of when it was delivered) 
            in an ISO 8601 formatted string.

    #
    # Party Webhook schemas
    #

    PartyWebhookRequest:
      allOf: 
      - $ref: '#/components/schemas/WebhookBase'
      - type: object
        description: JSON schema used in outbound webhook requests for Party changes
        required: [ data ]
        properties:
          data:
            $ref: '#/components/schemas/PartyWebhookData'

    PartyWebhookData:
      type: object
      description: Data sent inside a webhook request envelope for party changes
      required: [ party ]
      properties: 
        party:
          $ref: "#/components/schemas/ResourceRef"
        client:
          $ref: "#/components/schemas/ResourceRef"

    #
    # Matter Webhook schemas
    #

    MatterWebhookRequest:
      allOf: 
        - $ref: '#/components/schemas/WebhookBase'
        - type: object
          description: JSON schema used in outbound webhook requests for Matter changes
          required: [ data ]
          properties:
            data:
              $ref: '#/components/schemas/MatterWebhookData'

    MatterWebhookData:
      type: object
      description: Data sent inside a webhook request envelope for Matter changes
      required: [ party, client, matter ]
      properties: 
        party:
          $ref: "#/components/schemas/ResourceRef"
        client:
          $ref: "#/components/schemas/ResourceRef"
        matter:
          $ref: "#/components/schemas/ResourceRef"

    #
    # Document Webhook schemas
    #

    DocumentWebhookRequest:
      allOf: 
        - $ref: '#/components/schemas/WebhookBase'
        - type: object
          description: JSON schema used in outbound webhook requests for Document changes
          required: [ data ]
          properties:
            data:
              $ref: '#/components/schemas/DocumentWebhookData'

    DocumentWebhookData:
      allOf:
      - $ref: '#/components/schemas/DocumentLocationData'
      - type: object
        required: [ document ]
        properties:
          document:
            $ref: '#/components/schemas/DocumentData'

    #
    # Document Moved Schemas
    #

    DocumentMovedWebhookRequest:
      allOf: 
        - $ref: '#/components/schemas/WebhookBase'
        - type: object
          description: JSON schema used in outbound webhook requests for Document moves
          required: [ data ]
          properties:
            data:
              $ref: '#/components/schemas/DocumentMovedWebhookData'

    DocumentMovedWebhookData:
      type: object
      required: [ from, to ]
      properties: 
        document:
          $ref: '#/components/schemas/DocumentData'
        from:
          $ref: '#/components/schemas/DocumentLocationData'
        to:
          $ref: '#/components/schemas/DocumentLocationData'

    #
    # Shared Document Schema
    #

    DocumentData:
      type: object
      required: [ id, number, categories ]
      properties: 
        id:
          type: string
          format: uuid
          description: The ID of the resource
        number:
          type: string
          description: The resource's natural key or user reference
        categories:
          type: array
          items:
            type: string
        mimeType:
          type: string
          description: The MIME type for the file if known
        fileExtension:
          type: [string, null]
          description: The file name extension, e.g. 'pdf'
        contentChanged:
          type: [boolean, null]
          description: |
            For 'document.updated' events, this flag indicates if the binary file contents
            have changed. Only download the updated file if this flag is true.
    DocumentLocationData:
      type: object
      required: [ party ]
      properties: 
        party:
          $ref: "#/components/schemas/ResourceRef"
        client:
          $ref: "#/components/schemas/ResourceRef"
        matter:
          $ref: "#/components/schemas/ResourceRef"

    ResourceRef:
      type: object
      required: [ id, number ]
      properties: 
        id:
          type: string
          format: uuid
          description: The ID of the resource
        number:
          type: string
          description: The resource's natural key or user reference
